[project]
name = "neural"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "albumentations>=2.0.8",
    "graphviz>=0.21",
    "ipykernel<7.0.0",
    "keras>=3.14.1",
    "nbformat>=5.10.4",
    "opencv-python>=4.13.0.92",
    "plotly>=6.7.0",
    "pydot>=4.0.1",
    "scikit-learn>=1.8.0",
    "seaborn>=0.13.2",
    "tensorboard>=2.20.0",
    "torch>=2.11.0",
    "torchvision>=0.26.0",
]

[[tool.uv.index]]
name = "torch"
url = "https://download.pytorch.org/whl/cu128"
